-- ============================================================
-- MIGRATION 003: Gamification Tables
-- achievement_definitions, daily_missions, xp_events,
-- streaks, user_achievements
-- ============================================================

-- ─── ACHIEVEMENT_DEFINITIONS ──────────────────────────────────────────────
-- Central catalog of all achievable badges. Stored in DB (not just code)
-- so achievements can be added/modified without code deploys.
-- Conditions are evaluated server-side in check_and_unlock_achievements().

CREATE TABLE public.achievement_definitions (
  key         TEXT        PRIMARY KEY,
  name        TEXT        NOT NULL,
  description TEXT        NOT NULL,
  icon        TEXT        NOT NULL DEFAULT 'Trophy',
  color_hex   TEXT        NOT NULL DEFAULT '#FFD166',
  xp_reward   SMALLINT    NOT NULL DEFAULT 100,
  is_active   BOOLEAN     NOT NULL DEFAULT TRUE,
  is_secret   BOOLEAN     NOT NULL DEFAULT FALSE,
  sort_order  SMALLINT    NOT NULL DEFAULT 99,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  public.achievement_definitions          IS 'Badge catalog. check_and_unlock_achievements() evaluates conditions against this table.';
COMMENT ON COLUMN public.achievement_definitions.is_secret IS 'Secret achievements are shown as "???" in UI until unlocked.';


-- ─── DAILY_MISSIONS ───────────────────────────────────────────────────────
-- Generated by generate_daily_missions() each day per user.
-- Max 3 missions per user per day (enforced by user_settings + function logic).
-- UNIQUE constraint prevents duplicate mission generation if called twice.
-- target_entity_id is polymorphic: points to user_chapters.id or subjects.id.

CREATE TABLE public.daily_missions (
  id                  UUID               PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id             UUID               NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  mission_date        DATE               NOT NULL DEFAULT CURRENT_DATE,
  type                mission_type_enum  NOT NULL,
  target_entity_type  entity_type_enum   NOT NULL DEFAULT 'chapter',
  target_entity_id    UUID,
  title               TEXT               NOT NULL,
  description         TEXT,
  xp_reward           SMALLINT           NOT NULL DEFAULT 30 CHECK (xp_reward >= 0),
  status              mission_status_enum NOT NULL DEFAULT 'pending',
  completed_at        TIMESTAMPTZ,
  generated_at        TIMESTAMPTZ        NOT NULL DEFAULT NOW(),

  CONSTRAINT daily_missions_unique
    UNIQUE (user_id, mission_date, type, target_entity_id),

  CONSTRAINT daily_missions_completed_at_check
    CHECK (
      (status = 'completed' AND completed_at IS NOT NULL) OR
      (status != 'completed' AND completed_at IS NULL)
    )
);

COMMENT ON TABLE  public.daily_missions                   IS 'Daily missions generated by the Mission Engine. UNIQUE prevents duplicate generation.';
COMMENT ON COLUMN public.daily_missions.target_entity_id  IS 'Polymorphic. Points to user_chapters.id or subjects.id based on target_entity_type.';


-- ─── XP_EVENTS ────────────────────────────────────────────────────────────
-- Immutable append-only ledger of every XP transaction.
-- NEVER update or delete rows here — profiles.total_xp integrity depends on it.
-- Kept in sync with profiles.total_xp via the sync_xp_to_profile trigger.

CREATE TABLE public.xp_events (
  id            UUID               PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID               NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  event_type    xp_event_type_enum NOT NULL,
  xp_amount     SMALLINT           NOT NULL,
  reference_id  UUID,
  metadata      JSONB              NOT NULL DEFAULT '{}',
  created_at    TIMESTAMPTZ        NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.xp_events IS 'Immutable XP ledger. NEVER UPDATE OR DELETE. profiles.total_xp is synced via trigger.';


-- ─── STREAKS ──────────────────────────────────────────────────────────────
-- One row per user. Updated by update_streak() on any study activity.
-- last_activity_date is compared in user's LOCAL timezone (from profiles.timezone).
-- freeze_count is a stub for future "streak shield" shop items.

CREATE TABLE public.streaks (
  id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id             UUID        NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  current_streak      INTEGER     NOT NULL DEFAULT 0 CHECK (current_streak >= 0),
  longest_streak      INTEGER     NOT NULL DEFAULT 0 CHECK (longest_streak >= 0),
  last_activity_date  DATE,
  freeze_count        SMALLINT    NOT NULL DEFAULT 0 CHECK (freeze_count >= 0),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT streaks_user_unique        UNIQUE (user_id),
  CONSTRAINT streaks_longest_gte_current CHECK (longest_streak >= current_streak)
);

COMMENT ON TABLE public.streaks IS 'Streak tracking. update_streak() is called on every study activity. Uses profiles.timezone for correct midnight boundary.';


-- ─── USER_ACHIEVEMENTS ────────────────────────────────────────────────────
-- Append-only record of badges earned by each student.
-- check_and_unlock_achievements() writes here after evaluating conditions.
-- UNIQUE is critical: prevents duplicate badge grants even under concurrency.

CREATE TABLE public.user_achievements (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          UUID        NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  achievement_key  TEXT        NOT NULL REFERENCES public.achievement_definitions(key) ON DELETE RESTRICT,
  unlocked_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  notified         BOOLEAN     NOT NULL DEFAULT FALSE,

  CONSTRAINT user_achievements_unique UNIQUE (user_id, achievement_key)
);

COMMENT ON TABLE public.user_achievements IS 'Unlocked badges. Append-only: never delete rows. UNIQUE prevents duplicate grants.';
