-- ============================================================
-- MIGRATION 001: Enum Types
-- All custom ENUM types used across Atlas tables.
-- ENUMs enforce valid states at the DB layer.
-- To add new values later: ALTER TYPE x ADD VALUE 'new_val';
-- ============================================================

-- Notes completion state for a chapter
CREATE TYPE notes_status_enum AS ENUM (
  'none',
  'in_progress',
  'complete'
);

-- Mission types generated by the Mission Engine
CREATE TYPE mission_type_enum AS ENUM (
  'complete_notes',
  'review_chapter',
  'attempt_paper',
  'revisit_weak_topic',
  'confidence_check'
);

-- Lifecycle state of a daily mission
CREATE TYPE mission_status_enum AS ENUM (
  'pending',
  'completed',
  'skipped'
);

-- CAIE exam session identifiers
CREATE TYPE paper_session_enum AS ENUM (
  'feb_mar',
  'may_jun',
  'oct_nov'
);

-- All sources of XP (immutable event ledger)
CREATE TYPE xp_event_type_enum AS ENUM (
  'mission_complete',
  'notes_complete',
  'notes_in_progress',
  'paper_attempt',
  'streak_bonus_7',
  'streak_bonus_30',
  'streak_bonus_100',
  'achievement_unlock',
  'confidence_update',
  'friend_challenge_win',
  'manual_adjustment'
);

-- Social relationship state (future friends feature)
CREATE TYPE friendship_status_enum AS ENUM (
  'pending',
  'accepted',
  'blocked'
);

-- PvP challenge lifecycle (future)
CREATE TYPE challenge_status_enum AS ENUM (
  'pending',
  'active',
  'completed',
  'cancelled',
  'expired'
);

-- Polymorphic entity type reference
CREATE TYPE entity_type_enum AS ENUM (
  'chapter',
  'subject',
  'paper',
  'user'
);

-- Notification delivery types
CREATE TYPE notification_type_enum AS ENUM (
  'mission_reminder',
  'streak_warning',
  'achievement_unlock',
  'friend_request',
  'challenge_invite',
  'challenge_result',
  'level_up',
  'system'
);

-- Coin transaction types (future shop)
CREATE TYPE coin_transaction_type_enum AS ENUM (
  'earned_mission',
  'earned_streak',
  'earned_achievement',
  'spent_shop',
  'spent_challenge',
  'admin_adjustment'
);
